spring:
  mongodb:
    uri: mongodb+srv://hoseopi:password1234!@cluster0.5b3qylf.mongodb.net/?appName=Cluster0
    database: lotus
    representation:
      uuid: standard

s3:
  bucket: warm-tea-and-honest
  file-path: prod