spring:
  application:
    name: warm-tea-and-honest-reviews
  profiles:
    default: dev
  cloud:
    aws:
      credentials:
        access-key: AKIA3CMCCEEFPAWJPSVO
        secret-key: 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
      region:
        static: eu-west-2
      s3:
        enabled: true
  mongodb:
    uri: mongodb+srv://hoseopi:password1234!@cluster0.5b3qylf.mongodb.net/?appName=Cluster0
    database: lotus
    representation:
      uuid: standard
  docker:
    compose:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  tomcat:
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    connection-timeout: 10000
management:
  health:
    mongodb:
      enabled: false
app:
  upload:
    dir: public/covers


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG